import os
import json
import config
from ai_service import analyze_bug

# 10 Enterprise/B2B Test Cases with their expectations
test_cases = [
    {
        "id": 1,
        "title": "Corporate SSO Authentication Failure",
        "description": "Employees across multiple business units are unable to authenticate through Azure Active Directory SSO after the latest identity provider configuration update.",
        "source_team": "IT Support",
        "expected": {
            "severity": "Critical",
            "priority": "P0",
            "area": "Authentication",
            "recommended_team": "Security Team"
        }
    },
    {
        "id": 2,
        "title": "SAP Order Synchronization Failure",
        "description": "Customer orders created in SAP are not being synchronized to the internal order management platform after the middleware upgrade.",
        "source_team": "QA",
        "expected": {
            "area": "ERP Integration",
            "recommended_team": "Backend Team"
        }
    },
    {
        "id": 3,
        "title": "Production Kubernetes Node Failure",
        "description": "Two worker nodes in the production Kubernetes cluster entered NotReady state causing service degradation across analytics workloads.",
        "source_team": "DevOps",
        "expected": {
            "severity": "Critical",
            "priority": "P0",
            "area": "Infrastructure",
            "recommended_team": "DevOps Team"
        }
    },
    {
        "id": 4,
        "title": "Database Replication Delay",
        "description": "The PostgreSQL read replica is experiencing replication lag exceeding 45 minutes causing stale reports in business dashboards.",
        "source_team": "Developer",
        "expected": {
            "area": "Database",
            "recommended_team": "Database Team"
        }
    },
    {
        "id": 5,
        "title": "Role-Based Access Control Bypass",
        "description": "Users assigned to the Finance Analyst role can access payroll administration screens through direct URL manipulation.",
        "source_team": "Security",
        "expected": {
            "severity": "Critical",
            "priority": "P0",
            "area": "Security",
            "recommended_team": "Security Team"
        }
    },
    {
        "id": 6,
        "title": "API Gateway Rate Limit Misconfiguration",
        "description": "The API gateway is rejecting legitimate partner traffic due to incorrect throttling policies deployed during the latest release.",
        "source_team": "QA",
        "expected": {
            "area": "API",
            "recommended_team": "Backend Team"
        }
    },
    {
        "id": 7,
        "title": "Missing Production Alerts",
        "description": "Critical application failures are occurring in production but no alerts are being generated by the monitoring platform.",
        "source_team": "DevOps",
        "expected": {
            "area": "Monitoring",
            "recommended_team": "DevOps Team"
        }
    },
    {
        "id": 8,
        "title": "ETL Pipeline Failure",
        "description": "Nightly ETL jobs are failing to load transactional data into the enterprise data warehouse causing reporting delays.",
        "source_team": "Data Engineering",
        "expected": {
            "area": "Data Pipeline",
            "recommended_team": "Database Team"
        }
    },
    {
        "id": 9,
        "title": "Cloud Storage Access Failure",
        "description": "Production applications are unable to access object storage buckets following a cloud IAM policy update.",
        "source_team": "IT Support",
        "expected": {
            "area": "Cloud",
            "recommended_team": "Infrastructure Team"
        }
    },
    {
        "id": 10,
        "title": "Audit Log Retention Violation",
        "description": "Application audit logs are being deleted after 30 days instead of the mandated 180-day retention period required by compliance policy.",
        "source_team": "Compliance",
        "expected": {
            "area": "Compliance",
            "recommended_team": "Security Team"
        }
    }
]

def run_tests():
    print("==================================================")
    print("STARTING GEMINI ENTERPRISE VALIDATION SCENARIOS")
    print("==================================================\n")
    
    # Check if GEMINI_API_KEY is set
    api_key = config.GEMINI_API_KEY
    if not api_key:
        print("WARNING: GEMINI_API_KEY is not set in config.")
        print("Please configure GEMINI_API_KEY in your .env file before running this test.\n")
        return
        
    total_checks = 0
    passed_checks = 0
    successful_classifications = 0
    ai_service_failures = 0
    misclassifications = []
    
    for tc in test_cases:
        print(f"--- TEST CASE {tc['id']}: {tc['title']} ---")
        print(f"Description: {tc['description']}")
        print(f"Source Team: {tc['source_team']}")
        print("Calling analyze_bug_with_gemini()...")
        
        # Call the service function (this will automatically print [RAW OUTPUT])
        result = analyze_bug(tc["title"], tc["description"], tc["source_team"])
        
        print("[PARSED JSON OUTPUT]")
        print(json.dumps(result, indent=2))
        
        # Check if AI was unavailable
        if result.get("classification_status") == "AI_UNAVAILABLE" or result.get("model_used") == "Unavailable":
            ai_service_failures += 1
            print("\n[CLASSIFICATION STATUS]")
            print("  * AI service was UNAVAILABLE for this test case.")
        else:
            successful_classifications += 1
            print("\n[CLASSIFICATION STATUS]")
            for field, expected_val in tc["expected"].items():
                actual_val = result.get(field)
                total_checks += 1
                if actual_val == expected_val:
                    print(f"  * {field.capitalize()}: Expected '{expected_val}', Got '{actual_val}' -> PASS")
                    passed_checks += 1
                else:
                    print(f"  * {field.capitalize()}: Expected '{expected_val}', Got '{actual_val}' -> FAIL [X]")
                    misclassifications.append({
                        "test_case_id": tc["id"],
                        "title": tc["title"],
                        "field": field,
                        "expected": expected_val,
                        "actual": actual_val
                    })
        
        # Print extra metrics
        print(f"  * Confidence: {result.get('confidence')}%")
        print(f"  * Model Used: {result.get('model_used')}")
        print("==================================================\n")
        
    # Calculate accuracy
    accuracy = (passed_checks / total_checks) * 100 if total_checks > 0 else 0
    print("==================================================")
    print("ENTERPRISE CLASSIFICATION ACCURACY SUMMARY")
    print("==================================================")
    print(f"Successful Classifications (Online): {successful_classifications}")
    print(f"AI Service Failures (Offline): {ai_service_failures}")
    print(f"Total Active Checks: {total_checks}")
    print(f"Passed Checks: {passed_checks}")
    print(f"Accuracy Rate: {accuracy:.2f}%")
    
    if misclassifications:
        print("\nMISCLASSIFICATIONS:")
        for mc in misclassifications:
            print(f"  - TC {mc['test_case_id']} ({mc['title']}) [{mc['field'].upper()}]: Expected '{mc['expected']}', Got '{mc['actual']}'")
    elif total_checks > 0:
        print("\nAll online expectations matched perfectly! Accuracy is 100.00%.")
    else:
        print("\nNo online classifications were executed to calculate accuracy.")
    print("==================================================\n")

def run_router_validation_tests():
    print("==================================================")
    print("STARTING DEDICATED AI ROUTER VALIDATION TESTS")
    print("==================================================\n")
    
    import ai_service
    
    # Save original functions
    orig_gemini_func = ai_service.analyze_bug_with_gemini
    orig_groq_func = ai_service.analyze_bug_with_groq
    
    title = "Router Validation Bug"
    desc = "Application auth token validation fails causing access errors."
    source_team = "Security"
    
    # --- Test 1: Normal Gemini Success ---
    print("--- Test 1: Normal Gemini Success ---")
    print("Expecting Gemini primary execution success...")
    
    # Mock Gemini to return success
    def mock_gemini_success(t, d, s):
        return {
            "severity": "High",
            "priority": "P1",
            "area": "Security",
            "source_team": s,
            "recommended_team": "Security Team",
            "root_cause": "Mocked Gemini root cause",
            "suggested_fix": "Mocked Gemini suggested fix",
            "confidence": 90,
            "model_used": "Gemini",
            "router_status": "PRIMARY_SUCCESS",
            "classification_status": "SUCCESS"
        }
    
    ai_service.analyze_bug_with_gemini = mock_gemini_success
    
    res1 = analyze_bug(title, desc, source_team)
    print(f"Result model_used: {res1.get('model_used')}")
    print(f"Result router_status: {res1.get('router_status')}")
    print(f"Result classification_status: {res1.get('classification_status')}")
    assert res1.get("model_used") == "Gemini", f"Expected Gemini, got {res1.get('model_used')}"
    assert res1.get("router_status") == "PRIMARY_SUCCESS", f"Expected PRIMARY_SUCCESS, got {res1.get('router_status')}"
    print("Test 1: PASS\n")
    
    # --- Test 2: Force Gemini Failure ---
    print("--- Test 2: Force Gemini Failure ---")
    print("Forcing Gemini failure. Expecting fallback to Groq...")
    
    # Mock Gemini to fail
    def mock_gemini_fail(t, d, s):
        raise ValueError("Simulated Gemini API error")
        
    # Mock Groq to succeed
    def mock_groq_success(t, d, s):
        return {
            "severity": "High",
            "priority": "P1",
            "area": "Security",
            "source_team": s,
            "recommended_team": "Security Team",
            "root_cause": "Mocked Groq root cause",
            "suggested_fix": "Mocked Groq suggested fix",
            "confidence": 90,
            "model_used": "Groq",
            "router_status": "FALLBACK_TRIGGERED",
            "classification_status": "SUCCESS"
        }
        
    ai_service.analyze_bug_with_gemini = mock_gemini_fail
    ai_service.analyze_bug_with_groq = mock_groq_success
    
    res2 = analyze_bug(title, desc, source_team)
    print(f"Result model_used: {res2.get('model_used')}")
    print(f"Result router_status: {res2.get('router_status')}")
    print(f"Result classification_status: {res2.get('classification_status')}")
    assert res2.get("model_used") == "Groq", f"Expected Groq, got {res2.get('model_used')}"
    assert res2.get("router_status") == "FALLBACK_TRIGGERED", f"Expected FALLBACK_TRIGGERED, got {res2.get('router_status')}"
    print("Test 2: PASS\n")
    
    # --- Test 3: Force Gemini + Groq Failure ---
    print("--- Test 3: Force Gemini + Groq Failure ---")
    print("Forcing both Gemini and Groq failure. Expecting fallback default values...")
    
    # Mock both to fail
    def mock_groq_fail(t, d, s):
        raise ValueError("Simulated Groq API error")
        
    ai_service.analyze_bug_with_gemini = mock_gemini_fail
    ai_service.analyze_bug_with_groq = mock_groq_fail
    
    res3 = analyze_bug(title, desc, source_team)
    print(f"Result model_used: {res3.get('model_used')}")
    print(f"Result router_status: {res3.get('router_status')}")
    print(f"Result classification_status: {res3.get('classification_status')}")
    assert res3.get("model_used") == "Unavailable", f"Expected Unavailable, got {res3.get('model_used')}"
    assert res3.get("router_status") == "ALL_MODELS_FAILED", f"Expected ALL_MODELS_FAILED, got {res3.get('router_status')}"
    assert res3.get("classification_status") == "AI_UNAVAILABLE", f"Expected AI_UNAVAILABLE, got {res3.get('classification_status')}"
    print("Test 3: PASS\n")
    
    # Restore original functions
    ai_service.analyze_bug_with_gemini = orig_gemini_func
    ai_service.analyze_bug_with_groq = orig_groq_func
    
    print("==================================================")
    print("AI ROUTER VALIDATION TESTS COMPLETED SUCCESSFULLY")
    print("==================================================")

if __name__ == "__main__":
    run_tests()
    run_router_validation_tests()
